language: node_js
node_js:
  - 5.0.0
branches:
  only: 'master'
before_install:
  - npm install -g bower coffee-script browserify
before_script:
  - npm run update
  - npm run build
script:
  - echo "nothing"
